name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packges
        run: npm install
      - name: Deploy to GitHub Packges
        shell: bash
        env:
          MY_EMAIL: ${{secrets.MY_EMAIL}}
          MY_USERNAME: ${{secrets.MY_USERNAME}}
          MY_ACCESS_TOKEN: ${{secrets.MY_ACCESS_TOKEN}}
        run: |
          echo ${{secrets.MY_EMAIL}}
          git config --global user.email "$MY_EMAIL"
          git config --global user.name "$MY_USERNAME"
          git remote set-url origin https://$MY_ACCESS_TOKEN@github.com/$MYUSERNAME/saarcohenn.github.io.git
          yarn deploy
