name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packges
        run: npm install
      - name: Deploy to GitHub Packges
        run: |
          git config --global user.email ${{ github-pages.MY_EMAIL }}
          git config --global user.name ${{ github-pages.MY_USERNAME }}
          git remote set-url origin https://${{ github-pages.MY_ACCESS_TOKEN }}@github.com/${{ github-pages.GITHUB_USERNAME}}/saarcohenn.github.io.git
          yarn deploy
