name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packges
        run: npm install
      - name: Deploy to GitHub Packges
        run: |
          echo ${{secrets.MY_EMAIL}}
          git config --global user.email "saar.cohenn@gmail.com"
          git config --global user.name "saarcohenn"
          git remote set-url origin https://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@github.com/saarcohenn/saarcohenn.github.io.git
          yarn deploy
